# Introducción a Numpy

In [32]:
import numpy as np

In [33]:
np.array([10,20,24,5,50,10,15])

array([10, 20, 24,  5, 50, 10, 15])

In [34]:
a = np.array([11,12,13,14,15,50,52,54,77,88,43,100])
a[4]

15

In [35]:
a[3:]

array([ 14,  15,  50,  52,  54,  77,  88,  43, 100])

In [36]:
a[3:7]

array([14, 15, 50, 52])

In [37]:
a[1::4]

array([12, 50, 88])

In [38]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [39]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [40]:
ones=np.ones((3,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
type(ones)

numpy.ndarray

In [42]:
type(ones[1])

numpy.ndarray

In [43]:
type(ones[2][2])

numpy.float64

In [44]:
np.linspace(3, 10, 100)

array([ 3.        ,  3.07070707,  3.14141414,  3.21212121,  3.28282828,
        3.35353535,  3.42424242,  3.49494949,  3.56565657,  3.63636364,
        3.70707071,  3.77777778,  3.84848485,  3.91919192,  3.98989899,
        4.06060606,  4.13131313,  4.2020202 ,  4.27272727,  4.34343434,
        4.41414141,  4.48484848,  4.55555556,  4.62626263,  4.6969697 ,
        4.76767677,  4.83838384,  4.90909091,  4.97979798,  5.05050505,
        5.12121212,  5.19191919,  5.26262626,  5.33333333,  5.4040404 ,
        5.47474747,  5.54545455,  5.61616162,  5.68686869,  5.75757576,
        5.82828283,  5.8989899 ,  5.96969697,  6.04040404,  6.11111111,
        6.18181818,  6.25252525,  6.32323232,  6.39393939,  6.46464646,
        6.53535354,  6.60606061,  6.67676768,  6.74747475,  6.81818182,
        6.88888889,  6.95959596,  7.03030303,  7.1010101 ,  7.17171717,
        7.24242424,  7.31313131,  7.38383838,  7.45454545,  7.52525253,
        7.5959596 ,  7.66666667,  7.73737374,  7.80808081,  7.87

In [45]:
b = np.array([['x', 'y', 'z'], ['a', 'b', 'c']])
print(b)
print(type(b))
print(f'Forma: {b.shape}')
print(f'Dimensión: {b.ndim}')

[['x' 'y' 'z']
 ['a' 'b' 'c']]
<class 'numpy.ndarray'>
Forma: (2, 3)
Dimensión: 2


In [46]:
c = [12,4,5,6,3,1,56,67,3,23456,678,43,2,1,5,6]
np.sort(c)

array([    1,     1,     2,     3,     3,     4,     5,     5,     6,
           6,    12,    43,    56,    67,   678, 23456])

In [47]:
cabeceras = [('nombre', 'S10'), ('edad', int)]
datos = [('Juan', 10), ('Maria', 70), ('Javier', 42), ('Lisney', 20)]
usuarios = np.array(datos, dtype = cabeceras)

np.sort(usuarios, order = 'edad')

array([(b'Juan', 10), (b'Lisney', 20), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

In [48]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [51]:
np.full((3,5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [52]:
np.diag([0,3,9,10])

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])

## Reto

Realizar un arreglo de 3 dimensiones y ordernarlo por Nombre, Edad, País

In [57]:
cabeceras = [('nombre', 'S10'), ('edad', int), ('pais', 'S15')]
datos = [('Juan', 10, 'Colombia'), ('Maria', 70, 'Chile'), ('Javier', 42,'Ecuador'), ('Lisney', 20, 'Peru')]
usuarios = np.array(datos, dtype = cabeceras)

np.sort(usuarios, order = 'pais')

array([(b'Maria', 70, b'Chile'), (b'Juan', 10, b'Colombia'),
       (b'Javier', 42, b'Ecuador'), (b'Lisney', 20, b'Peru')],
      dtype=[('nombre', 'S10'), ('edad', '<i8'), ('pais', 'S15')])